
mybatis.mapperLocations: classpath:mapper/*.xml

spring.data.mongodb.uri: mongodb://marketcenter:marketcenter@10.250.80.35:27017/marketcenter
# redis 配置
spring.redis.database: 1
spring.redis.host: 10.250.80.45
spring.redis.port: 6379
spring.redis.password: Redis@123456
spring.redis.pool.max-active: 8
spring.redis.pool.max-wait: -1
spring.redis.pool.max-idle: 8
spring.redis.pool.min-idle: 0
spring.redis.timeout: 5000





