spring:
  datasource:
    url: jdbc:mysql://10.250.80.12:3306/fbi_hub?useUnicode=true&characterEncoding=utf-8
    username: fbi_w
    password: Fbi@123456

mybatis.mapperLocations: classpath:mapper/*.xml

spring.data.mongodb.uri: mongodb://marketcenter:marketcenter@10.250.80.35:27017/marketcenter